remote_theme: "jekyll/minima@1e8a445"
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag

author:
  name: Yuri Braz
  email: ybraz@live.com

title: Yuri Braz
description: "É justo que muito custe, o que muito vale."

minima:
#   Minima color scheme.
#     Options are `light`, `dark`, and `auto` (which follows system settings
  skin: auto

#   Navigation pages.
nav_pages:
    - about.md
#
#   Set to `true` to show excerpts on the homepage.
show_excerpts: true
#
#   Minima date format.
#     The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
#     Refer to https://shopify.github.io/liquid/filters/date/ for valid values
date_format: "%b-%d-%Y"

#
#   Hide syndication feed subscription link.
#     RSS / Atom feed link is always rendered as the last item of social-links
#     list. Set below key to `true` to not have the link to feed rendered as
#     part of social-links list.
hide_site_feed_link: true